#!/usr/bin/env bash
# =============================================================================
# Garage bootstrap — cluster layout, access key, buckets, CORS
# =============================================================================
# A fresh Garage node serves nothing until it has a layout, and the NEON API
# only checks that its buckets exist (it never creates them), so this has to
# happen once before the API can start. Every step is guarded, so re-running is
# free.
#
#   bootstrap-garage.sh <deploy.env> <garage.env> <compose-file>
#
# The access key Garage mints on the first run is written to <garage.env>,
# which the API reads as an env_file.
# =============================================================================
set -euo pipefail

DEPLOY_ENV="$1"
GARAGE_ENV="$2"
COMPOSE_FILE="$3"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

COMPOSE=(docker compose --env-file "$DEPLOY_ENV" -f "$COMPOSE_FILE")
G=("${COMPOSE[@]}" exec -T garage /usr/local/bin/garage)

log() { echo "[garage $(date -u +%H:%M:%S)] $*"; }

BUCKET_MEDIA=neon-media
BUCKET_BACKUPS=neon-backups
BUCKET_RECORDINGS=neon-recordings
KEY_NAME=neon

# --- wait for the daemon -----------------------------------------------------
log "waiting for the Garage daemon"
for _ in $(seq 1 60); do
  if "${G[@]}" status >/dev/null 2>&1; then break; fi
  sleep 2
done
"${G[@]}" status >/dev/null 2>&1 || { echo "[garage] daemon never answered" >&2; exit 1; }

# --- layout ------------------------------------------------------------------
NODE_ID="$("${G[@]}" node id -q | cut -d@ -f1 | tr -d '\r')"
if "${G[@]}" layout show 2>/dev/null | grep -q "${NODE_ID:0:16}"; then
  log "layout already assigns a role to this node"
else
  log "assigning layout role to ${NODE_ID:0:16}…"
  "${G[@]}" layout assign -z dc1 -c 200G "$NODE_ID"
  VERSION="$("${G[@]}" layout show | grep -oE 'apply --version [0-9]+' | grep -oE '[0-9]+$' | tail -1)"
  "${G[@]}" layout apply --version "${VERSION:-1}"
  log "layout applied (version ${VERSION:-1})"
  sleep 3
fi

# --- buckets -----------------------------------------------------------------
for b in "$BUCKET_MEDIA" "$BUCKET_BACKUPS" "$BUCKET_RECORDINGS"; do
  if "${G[@]}" bucket info "$b" >/dev/null 2>&1; then
    log "bucket $b exists"
  else
    log "creating bucket $b"
    "${G[@]}" bucket create "$b"
  fi
done

# --- access key --------------------------------------------------------------
if "${G[@]}" key info "$KEY_NAME" >/dev/null 2>&1; then
  log "key '$KEY_NAME' exists"
else
  log "creating key '$KEY_NAME'"
  "${G[@]}" key create "$KEY_NAME" >/dev/null
fi

KEY_INFO="$("${G[@]}" key info "$KEY_NAME" --show-secret)"
ACCESS_KEY="$(echo "$KEY_INFO" | grep -iE '^Key ID:' | awk '{print $NF}' | tr -d '\r')"
SECRET_KEY="$(echo "$KEY_INFO" | grep -iE '^Secret key:' | awk '{print $NF}' | tr -d '\r')"
[ -n "$ACCESS_KEY" ] && [ -n "$SECRET_KEY" ] || { echo "[garage] could not read the key back" >&2; exit 1; }

for b in "$BUCKET_MEDIA" "$BUCKET_BACKUPS" "$BUCKET_RECORDINGS"; do
  "${G[@]}" bucket allow --read --write --owner "$b" --key "$KEY_NAME" >/dev/null
done
log "key '$KEY_NAME' ($ACCESS_KEY) owns all three buckets"

# --- hand the credentials to the API ----------------------------------------
umask 077
cat > "$GARAGE_ENV" <<ENV
# Generated by bootstrap-garage.sh — do not edit, do not commit.
# Regenerate by deleting this file and re-running the startup script.
S3_ACCESS_KEY=$ACCESS_KEY
S3_SECRET_KEY=$SECRET_KEY
ENV
log "credentials written to $GARAGE_ENV"

# --- CORS --------------------------------------------------------------------
# Uploads and downloads are pre-signed straight to the browser, so the buckets
# need to accept cross-origin requests from the app's own origin.
if "${COMPOSE[@]}" run --rm -T api node - < "$HERE/put-bucket-cors.cjs"; then
  log "bucket CORS configured"
else
  log "WARNING: setting bucket CORS failed — file upload/download from the browser may be blocked"
fi
