#!/usr/bin/env bash
#
# NEON Reverse Proxy Configuration Generator
#

set -e

PROXY_TYPE="${1:-nginx}"
DOMAIN="${2:-neon.example.com}"
LIVEKIT_DOMAIN="${3:-livekit.example.com}"
LIVEKIT_SEPARATE="${4:-true}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
OUTPUT_DIR="$PROJECT_ROOT/docker/proxy-configs"

mkdir -p "$OUTPUT_DIR"

# Colors
GREEN='\033[0;32m'
CYAN='\033[0;36m'
NC='\033[0m'

generate_nginx() {
    cat > "$OUTPUT_DIR/nginx.conf" << EOF
# NEON Nginx Configuration
# Generated by NEON setup script
#
# Installation:
#   1. Copy this file to /etc/nginx/sites-available/neon.conf
#   2. Create symlink: ln -s /etc/nginx/sites-available/neon.conf /etc/nginx/sites-enabled/
#   3. Install certbot: apt install certbot python3-certbot-nginx
#   4. Get SSL certificate: certbot --nginx -d $DOMAIN${LIVEKIT_SEPARATE:+ -d $LIVEKIT_DOMAIN}
#   5. Reload nginx: nginx -t && systemctl reload nginx

# Rate limiting
limit_req_zone \$binary_remote_addr zone=api_limit:10m rate=10r/s;
limit_req_zone \$binary_remote_addr zone=auth_limit:10m rate=5r/m;

# Upstream servers
upstream neon_api {
    server 127.0.0.1:3001;
    keepalive 32;
}

upstream neon_web {
    server 127.0.0.1:3000;
    keepalive 32;
}

upstream neon_livekit {
    server 127.0.0.1:7880;
    keepalive 32;
}

# Main NEON server
server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN;

    # Redirect to HTTPS
    location / {
        return 301 https://\$server_name\$request_uri;
    }

    # ACME challenge for Let's Encrypt
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name $DOMAIN;

    # SSL certificates (managed by certbot)
    ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/$DOMAIN/chain.pem;

    # SSL configuration
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_session_tickets off;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;

    # HSTS
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    # Security headers
    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options DENY always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;

    # Gzip compression
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css text/xml application/json application/javascript application/rss+xml application/atom+xml image/svg+xml;

    # API routes
    location /api/ {
        limit_req zone=api_limit burst=20 nodelay;

        proxy_pass http://neon_api;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    # Auth rate limiting
    location /api/auth/ {
        limit_req zone=auth_limit burst=5 nodelay;

        proxy_pass http://neon_api;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    # WebSocket (Socket.io)
    location /socket.io/ {
        proxy_pass http://neon_api;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        # WebSocket timeouts
        proxy_connect_timeout 7d;
        proxy_send_timeout 7d;
        proxy_read_timeout 7d;
    }
EOF

    if [ "$LIVEKIT_SEPARATE" != "true" ]; then
        cat >> "$OUTPUT_DIR/nginx.conf" << EOF

    # LiveKit (if on same domain)
    location /livekit/ {
        rewrite ^/livekit/(.*) /\$1 break;
        proxy_pass http://neon_livekit;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
EOF
    fi

    cat >> "$OUTPUT_DIR/nginx.conf" << EOF

    # Web client (default)
    location / {
        proxy_pass http://neon_web;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        # Cache static assets
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
            proxy_pass http://neon_web;
            expires 1y;
            add_header Cache-Control "public, immutable";
        }
    }
}
EOF

    if [ "$LIVEKIT_SEPARATE" = "true" ]; then
        cat >> "$OUTPUT_DIR/nginx.conf" << EOF

# LiveKit server (separate domain)
server {
    listen 80;
    listen [::]:80;
    server_name $LIVEKIT_DOMAIN;

    location / {
        return 301 https://\$server_name\$request_uri;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name $LIVEKIT_DOMAIN;

    ssl_certificate /etc/letsencrypt/live/$LIVEKIT_DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$LIVEKIT_DOMAIN/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/$LIVEKIT_DOMAIN/chain.pem;

    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_session_tickets off;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    location / {
        proxy_pass http://neon_livekit;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        # WebRTC timeouts
        proxy_connect_timeout 7d;
        proxy_send_timeout 7d;
        proxy_read_timeout 7d;
    }
}
EOF
    fi

    echo -e "${GREEN}✓${NC} Generated: $OUTPUT_DIR/nginx.conf"
}

generate_caddy() {
    cat > "$OUTPUT_DIR/Caddyfile" << EOF
# NEON Caddy Configuration
# Generated by NEON setup script
#
# Installation:
#   1. Copy this file to /etc/caddy/Caddyfile
#   2. Reload Caddy: systemctl reload caddy
#
# Caddy will automatically obtain and renew SSL certificates.

$DOMAIN {
    # API routes
    handle /api/* {
        reverse_proxy localhost:3001
    }

    # WebSocket (Socket.io)
    handle /socket.io/* {
        reverse_proxy localhost:3001
    }
EOF

    if [ "$LIVEKIT_SEPARATE" != "true" ]; then
        cat >> "$OUTPUT_DIR/Caddyfile" << EOF

    # LiveKit (same domain)
    handle /livekit/* {
        uri strip_prefix /livekit
        reverse_proxy localhost:7880
    }
EOF
    fi

    cat >> "$OUTPUT_DIR/Caddyfile" << EOF

    # Web client (default)
    handle {
        reverse_proxy localhost:3000
    }

    # Security headers
    header {
        X-Content-Type-Options nosniff
        X-Frame-Options DENY
        Referrer-Policy strict-origin-when-cross-origin
        Strict-Transport-Security "max-age=31536000; includeSubDomains"
    }

    # Gzip compression
    encode gzip

    # Logging
    log {
        output file /var/log/caddy/neon.log
        format json
    }
}
EOF

    if [ "$LIVEKIT_SEPARATE" = "true" ]; then
        cat >> "$OUTPUT_DIR/Caddyfile" << EOF

# LiveKit server (separate domain)
$LIVEKIT_DOMAIN {
    reverse_proxy localhost:7880

    header {
        Strict-Transport-Security "max-age=31536000; includeSubDomains"
    }

    log {
        output file /var/log/caddy/livekit.log
        format json
    }
}
EOF
    fi

    echo -e "${GREEN}✓${NC} Generated: $OUTPUT_DIR/Caddyfile"
}

generate_haproxy() {
    cat > "$OUTPUT_DIR/haproxy.cfg" << EOF
# NEON HAProxy Configuration
# Generated by NEON setup script
#
# Installation:
#   1. Copy this file to /etc/haproxy/haproxy.cfg
#   2. Generate SSL certificate with certbot or similar
#   3. Combine cert: cat fullchain.pem privkey.pem > /etc/haproxy/certs/$DOMAIN.pem
#   4. Reload HAProxy: systemctl reload haproxy

global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

    # SSL settings
    ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384
    ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets
    tune.ssl.default-dh-param 2048

defaults
    log global
    mode http
    option httplog
    option dontlognull
    option http-server-close
    option forwardfor except 127.0.0.0/8
    option redispatch
    retries 3
    timeout connect 5s
    timeout client 50s
    timeout server 50s
    timeout http-request 10s
    timeout http-keep-alive 10s
    timeout queue 60s
    timeout tunnel 1h

# Stats page
listen stats
    bind *:8404
    stats enable
    stats uri /stats
    stats refresh 10s
    stats admin if LOCALHOST

# HTTP to HTTPS redirect
frontend http_front
    bind *:80
    mode http

    # ACME challenge
    acl is_acme path_beg /.well-known/acme-challenge/
    use_backend acme_backend if is_acme

    # Redirect everything else to HTTPS
    redirect scheme https code 301 if !is_acme

# HTTPS frontend
frontend https_front
    bind *:443 ssl crt /etc/haproxy/certs/$DOMAIN.pem alpn h2,http/1.1
    mode http

    # Security headers
    http-response set-header Strict-Transport-Security "max-age=31536000; includeSubDomains"
    http-response set-header X-Content-Type-Options nosniff
    http-response set-header X-Frame-Options DENY
    http-response set-header Referrer-Policy strict-origin-when-cross-origin

    # ACLs for routing
    acl is_api path_beg /api/
    acl is_websocket path_beg /socket.io/
    acl is_websocket_upgrade hdr(Upgrade) -i websocket
EOF

    if [ "$LIVEKIT_SEPARATE" != "true" ]; then
        cat >> "$OUTPUT_DIR/haproxy.cfg" << EOF
    acl is_livekit path_beg /livekit/
EOF
    fi

    cat >> "$OUTPUT_DIR/haproxy.cfg" << EOF

    # Backend selection
    use_backend neon_api if is_api
    use_backend neon_api if is_websocket
EOF

    if [ "$LIVEKIT_SEPARATE" != "true" ]; then
        cat >> "$OUTPUT_DIR/haproxy.cfg" << EOF
    use_backend neon_livekit if is_livekit
EOF
    fi

    cat >> "$OUTPUT_DIR/haproxy.cfg" << EOF
    default_backend neon_web
EOF

    if [ "$LIVEKIT_SEPARATE" = "true" ]; then
        cat >> "$OUTPUT_DIR/haproxy.cfg" << EOF

# LiveKit frontend (separate domain)
frontend livekit_https
    bind *:443 ssl crt /etc/haproxy/certs/$LIVEKIT_DOMAIN.pem alpn h2,http/1.1
    mode http
    acl is_livekit_domain hdr(host) -i $LIVEKIT_DOMAIN
    use_backend neon_livekit if is_livekit_domain
EOF
    fi

    cat >> "$OUTPUT_DIR/haproxy.cfg" << EOF

# Backends
backend neon_api
    mode http
    balance roundrobin
    option httpchk GET /api/health
    http-check expect status 200
    server api1 127.0.0.1:3001 check inter 5s

backend neon_web
    mode http
    balance roundrobin
    option httpchk GET /
    server web1 127.0.0.1:3000 check inter 5s

backend neon_livekit
    mode http
    balance roundrobin
    option httpchk GET /
    timeout tunnel 1h
    server livekit1 127.0.0.1:7880 check inter 5s

backend acme_backend
    mode http
    server acme 127.0.0.1:8080
EOF

    echo -e "${GREEN}✓${NC} Generated: $OUTPUT_DIR/haproxy.cfg"
}

generate_traefik() {
    # Static configuration
    cat > "$OUTPUT_DIR/traefik.yml" << EOF
# NEON Traefik Static Configuration
# Generated by NEON setup script
#
# Installation:
#   1. Copy traefik.yml to /etc/traefik/traefik.yml
#   2. Copy traefik-dynamic.yml to /etc/traefik/dynamic/neon.yml
#   3. Create acme.json: touch /etc/traefik/acme.json && chmod 600 /etc/traefik/acme.json
#   4. Start Traefik: systemctl start traefik

api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@$DOMAIN
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

log:
  level: INFO
  format: json

accessLog:
  format: json
EOF

    # Dynamic configuration
    cat > "$OUTPUT_DIR/traefik-dynamic.yml" << EOF
# NEON Traefik Dynamic Configuration

http:
  routers:
    # API Router
    neon-api:
      rule: "Host(\`$DOMAIN\`) && PathPrefix(\`/api\`)"
      service: neon-api
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      middlewares:
        - security-headers
        - rate-limit

    # WebSocket Router
    neon-websocket:
      rule: "Host(\`$DOMAIN\`) && PathPrefix(\`/socket.io\`)"
      service: neon-api
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
EOF

    if [ "$LIVEKIT_SEPARATE" != "true" ]; then
        cat >> "$OUTPUT_DIR/traefik-dynamic.yml" << EOF

    # LiveKit Router (same domain)
    neon-livekit:
      rule: "Host(\`$DOMAIN\`) && PathPrefix(\`/livekit\`)"
      service: neon-livekit
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      middlewares:
        - strip-livekit-prefix
EOF
    fi

    cat >> "$OUTPUT_DIR/traefik-dynamic.yml" << EOF

    # Web Client Router
    neon-web:
      rule: "Host(\`$DOMAIN\`)"
      service: neon-web
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      middlewares:
        - security-headers
      priority: 1
EOF

    if [ "$LIVEKIT_SEPARATE" = "true" ]; then
        cat >> "$OUTPUT_DIR/traefik-dynamic.yml" << EOF

    # LiveKit Router (separate domain)
    livekit:
      rule: "Host(\`$LIVEKIT_DOMAIN\`)"
      service: neon-livekit
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
EOF
    fi

    cat >> "$OUTPUT_DIR/traefik-dynamic.yml" << EOF

  services:
    neon-api:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:3001"
        healthCheck:
          path: /api/health
          interval: 10s

    neon-web:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:3000"

    neon-livekit:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:7880"

  middlewares:
    security-headers:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        contentTypeNosniff: true
        frameDeny: true
        referrerPolicy: strict-origin-when-cross-origin

    rate-limit:
      rateLimit:
        average: 100
        burst: 50
        period: 1s

    strip-livekit-prefix:
      stripPrefix:
        prefixes:
          - /livekit
EOF

    echo -e "${GREEN}✓${NC} Generated: $OUTPUT_DIR/traefik.yml"
    echo -e "${GREEN}✓${NC} Generated: $OUTPUT_DIR/traefik-dynamic.yml"
}

generate_apache() {
    cat > "$OUTPUT_DIR/apache.conf" << EOF
# NEON Apache Configuration
# Generated by NEON setup script
#
# Installation:
#   1. Enable required modules:
#      a2enmod proxy proxy_http proxy_wstunnel ssl headers rewrite
#   2. Copy this file to /etc/apache2/sites-available/neon.conf
#   3. Enable site: a2ensite neon
#   4. Get SSL with certbot: certbot --apache -d $DOMAIN${LIVEKIT_SEPARATE:+ -d $LIVEKIT_DOMAIN}
#   5. Reload Apache: systemctl reload apache2

# HTTP -> HTTPS redirect
<VirtualHost *:80>
    ServerName $DOMAIN
EOF

    if [ "$LIVEKIT_SEPARATE" = "true" ]; then
        cat >> "$OUTPUT_DIR/apache.conf" << EOF
    ServerAlias $LIVEKIT_DOMAIN
EOF
    fi

    cat >> "$OUTPUT_DIR/apache.conf" << EOF

    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

    # Let's Encrypt challenge
    Alias /.well-known/acme-challenge/ /var/www/certbot/.well-known/acme-challenge/
    <Directory "/var/www/certbot/.well-known/acme-challenge/">
        Options None
        AllowOverride None
        Require all granted
    </Directory>
</VirtualHost>

# Main NEON site
<VirtualHost *:443>
    ServerName $DOMAIN

    SSLEngine on
    SSLCertificateFile /etc/letsencrypt/live/$DOMAIN/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/$DOMAIN/privkey.pem

    # Modern SSL configuration
    SSLProtocol all -SSLv3 -TLSv1 -TLSv1.1
    SSLCipherSuite ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384
    SSLHonorCipherOrder off

    # Security headers
    Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains"
    Header always set X-Content-Type-Options nosniff
    Header always set X-Frame-Options DENY
    Header always set Referrer-Policy strict-origin-when-cross-origin

    # Enable WebSocket proxying
    RewriteEngine On

    # WebSocket (Socket.io)
    RewriteCond %{HTTP:Upgrade} websocket [NC]
    RewriteCond %{HTTP:Connection} upgrade [NC]
    RewriteRule ^/socket.io/(.*) ws://127.0.0.1:3001/socket.io/\$1 [P,L]

    # API routes
    ProxyPass /api/ http://127.0.0.1:3001/api/
    ProxyPassReverse /api/ http://127.0.0.1:3001/api/

    # Socket.io polling fallback
    ProxyPass /socket.io/ http://127.0.0.1:3001/socket.io/
    ProxyPassReverse /socket.io/ http://127.0.0.1:3001/socket.io/
EOF

    if [ "$LIVEKIT_SEPARATE" != "true" ]; then
        cat >> "$OUTPUT_DIR/apache.conf" << EOF

    # LiveKit (same domain)
    RewriteCond %{HTTP:Upgrade} websocket [NC]
    RewriteRule ^/livekit/(.*) ws://127.0.0.1:7880/\$1 [P,L]

    ProxyPass /livekit/ http://127.0.0.1:7880/
    ProxyPassReverse /livekit/ http://127.0.0.1:7880/
EOF
    fi

    cat >> "$OUTPUT_DIR/apache.conf" << EOF

    # Web client (default)
    ProxyPass / http://127.0.0.1:3000/
    ProxyPassReverse / http://127.0.0.1:3000/

    # Proxy settings
    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto "https"
    RequestHeader set X-Forwarded-Port "443"

    # Logging
    ErrorLog \${APACHE_LOG_DIR}/neon_error.log
    CustomLog \${APACHE_LOG_DIR}/neon_access.log combined
</VirtualHost>
EOF

    if [ "$LIVEKIT_SEPARATE" = "true" ]; then
        cat >> "$OUTPUT_DIR/apache.conf" << EOF

# LiveKit site (separate domain)
<VirtualHost *:443>
    ServerName $LIVEKIT_DOMAIN

    SSLEngine on
    SSLCertificateFile /etc/letsencrypt/live/$LIVEKIT_DOMAIN/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/$LIVEKIT_DOMAIN/privkey.pem

    SSLProtocol all -SSLv3 -TLSv1 -TLSv1.1
    SSLCipherSuite ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384
    SSLHonorCipherOrder off

    Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains"

    # WebSocket support
    RewriteEngine On
    RewriteCond %{HTTP:Upgrade} websocket [NC]
    RewriteCond %{HTTP:Connection} upgrade [NC]
    RewriteRule ^/(.*) ws://127.0.0.1:7880/\$1 [P,L]

    ProxyPass / http://127.0.0.1:7880/
    ProxyPassReverse / http://127.0.0.1:7880/

    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto "https"

    ErrorLog \${APACHE_LOG_DIR}/livekit_error.log
    CustomLog \${APACHE_LOG_DIR}/livekit_access.log combined
</VirtualHost>
EOF
    fi

    echo -e "${GREEN}✓${NC} Generated: $OUTPUT_DIR/apache.conf"
}

# Main
case "$PROXY_TYPE" in
    nginx)
        generate_nginx
        ;;
    caddy)
        generate_caddy
        ;;
    haproxy)
        generate_haproxy
        ;;
    traefik)
        generate_traefik
        ;;
    apache)
        generate_apache
        ;;
    all)
        generate_nginx
        generate_caddy
        generate_haproxy
        generate_traefik
        generate_apache
        ;;
    *)
        echo "Usage: $0 <nginx|caddy|haproxy|traefik|apache|all> <domain> <livekit_domain> <separate_livekit>"
        exit 1
        ;;
esac

echo ""
echo -e "${CYAN}Configuration files are in: $OUTPUT_DIR${NC}"
